"""empty message

Revision ID: 361c0eb81da9
Revises: 
Create Date: 2024-02-27 17:38:47.876312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361c0eb81da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
