"""empty message

Revision ID: 41d0f5166297
Revises: a7d465920722
Create Date: 2024-03-13 14:46:23.727989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d0f5166297'
down_revision = 'a7d465920722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('online_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
