"""empty message

Revision ID: a7d465920722
Revises: cadd5c1ca264
Create Date: 2024-02-27 20:57:16.323594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d465920722'
down_revision = 'cadd5c1ca264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nd_nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('us', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nstud_nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('us', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('username_fp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('us', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('username_fp')
    op.drop_table('nstud_nombre')
    op.drop_table('nd_nombre')
    # ### end Alembic commands ###
