"""empty message

Revision ID: cadd5c1ca264
Revises: 361c0eb81da9
Create Date: 2024-02-27 20:38:44.744158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd5c1ca264'
down_revision = '361c0eb81da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('np_nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('us', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('np_nombre')
    # ### end Alembic commands ###
