from App.Main.routes_about import *
from App.Main.routes_connexion import *
from App.Main.routes_home import *
from App.Main.routes_acces_interdit import *
from App.Main.routes_contact import *
from App.Main.routes_inscription import *
from App.Main.routes_meet import *
from App.Main.routes_password_rec import *
from App.Main.routes_payement import *
from App.Main.routes_reclamation import *
from App.Main.routes_retrait import *
from App.Main.routes_users import *
from App.Main.routes_profil import *
from App.Main.Models import *
from App.Main.Models import *