from App import db

class Demande(db.Model):
    id_demande = db.Column(db.Integer, primary_key=True)
    id_prof = db.Column(db.Integer, db.ForeignKey('prof.id'))
    id_live=db.Column(db.Integer, db.ForeignKey('live.id'))
    code=db.Column(db.String(500))
    prix=db.Column(db.Float)
    temps=db.Column(db.String(50))
    id_etudiant = db.Column(db.Integer, db.ForeignKey('etudiant.id'))
    date_demande = db.Column(db.DateTime)
    date_propose = db.Column(db.DateTime)
    confprof=db.Column(db.String(50),default="non")
    confetud=db.Column(db.String(50),default="non")
    ajout=db.Column(db.String(50),default="non")
    date_acc = db.Column(db.DateTime)
    date_fin = db.Column(db.DateTime)
    date1 = db.Column(db.DateTime)
    date2 = db.Column(db.DateTime)
    fichier = db.Column(db.String(50))
    discipline=db.Column(db.String(50))
    matiere = db.Column(db.String(50))
    chapiter = db.Column(db.String(50),default="Aucun chapitre mentionné")
    description = db.Column(db.Text)
    statut_demande = db.Column(db.String(50),default="enattente")
    statut_payement = db.Column(db.String(50),default="impayer")
    acceptation=db.Column(db.String(50),default="non")
    aj_e=db.Column(db.String(50),default="nouvelle")
    aj_p=db.Column(db.String(50),default="nouvelle")

class Live(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    id_moderateur = db.Column(db.Integer, db.ForeignKey('user.id'))
    id_demande = db.Column(db.Integer, db.ForeignKey('demande.id_demande'))

class StartLive(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_live = db.Column(db.Integer, db.ForeignKey('live.id'))
    date = db.Column(db.DateTime)
    id_participant = db.Column(db.Integer, db.ForeignKey('user.id'))
    code=db.Column(db.String(500))

class Offre(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom_offre = db.Column(db.String(50))
    description = db.Column(db.String(500))
    id_prof = db.Column(db.Integer, db.ForeignKey('prof.id'), nullable=False)
    matiere = db.Column(db.String(50), nullable=False)
    organisation = db.Column(db.String(100), nullable=True)
    type=db.Column(db.String(50))
    duree=db.Column(db.String(50), nullable=True)
    Tel=db.Column(db.String(50), nullable=True)
    horaire = db.Column(db.String(500))
    horaire_presentiel = db.Column(db.String(500))
    meet = db.Column(db.String(500))
    emplacement = db.Column(db.String(500))
    date_debut = db.Column(db.DateTime)
    date_fin = db.Column(db.DateTime)
    nombre_place_total = db.Column(db.Integer)
    prix = db.Column(db.Float)
    nombre_place_occupe = db.Column(db.Integer, default=0)
    image_1 = db.Column(db.String(500))
    image_2 = db.Column(db.String(500))

# Table SubscriptionOffre (table de souscription aux offres)
class SubscriptionOffre(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_offre = db.Column(db.Integer, db.ForeignKey('offre.id'), nullable=False)
    id_participant = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    offre = db.relationship('Offre', foreign_keys=[id_offre], backref=db.backref('subscriptions', lazy=True))

